# fly.toml app configuration file generated for dry-haze-4260 on 2023-09-19T19:49:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dry-haze-4260"
primary_region = "ams"

[build]

[env]
PORT="3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
