# fly.toml app configuration file generated for silent-dust-5319 on 2023-10-07T12:11:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "silent-dust-5319"
primary_region = "bos"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
